abstract class LoginState {}
class IniLog extends LoginState{}
class Login extends LoginState{}
class CreatAcc extends LoginState{}
class Forgot extends LoginState{}
class Glogin extends LoginState{}
class Flogin extends LoginState{}
class Sinout extends LoginState{}
class Loding extends LoginState{}
class Failed extends LoginState{}
class Showpassword extends LoginState{}