// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASOeH8LE1MUcBiGG08OhM28R-vk4hWqTY',
    appId: '1:405431192912:web:f9c2e17947faeb804af055',
    messagingSenderId: '405431192912',
    projectId: 'delarship-adf14',
    authDomain: 'delarship-adf14.firebaseapp.com',
    storageBucket: 'delarship-adf14.firebasestorage.app',
    measurementId: 'G-GR8EWQBD68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAok-W2sYf2U4CpPVtHJhaBa7857KX3Q98',
    appId: '1:405431192912:android:054a71de7f6464e34af055',
    messagingSenderId: '405431192912',
    projectId: 'delarship-adf14',
    storageBucket: 'delarship-adf14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj3uUQe4m0hTiGZG7IrkLM9n0sdAdUVzI',
    appId: '1:405431192912:ios:2f67b73d0dd771ad4af055',
    messagingSenderId: '405431192912',
    projectId: 'delarship-adf14',
    storageBucket: 'delarship-adf14.firebasestorage.app',
    androidClientId: '405431192912-2qvq8bjt34g6dieltbdg0oq8bh4ujvsv.apps.googleusercontent.com',
    iosClientId: '405431192912-9e0vvv566pmt60u0pcv6vkhgiampfci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.delarship',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj3uUQe4m0hTiGZG7IrkLM9n0sdAdUVzI',
    appId: '1:405431192912:ios:2f67b73d0dd771ad4af055',
    messagingSenderId: '405431192912',
    projectId: 'delarship-adf14',
    storageBucket: 'delarship-adf14.firebasestorage.app',
    androidClientId: '405431192912-2qvq8bjt34g6dieltbdg0oq8bh4ujvsv.apps.googleusercontent.com',
    iosClientId: '405431192912-9e0vvv566pmt60u0pcv6vkhgiampfci7.apps.googleusercontent.com',
    iosBundleId: 'com.example.delarship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASOeH8LE1MUcBiGG08OhM28R-vk4hWqTY',
    appId: '1:405431192912:web:36b5170ffcaf47fe4af055',
    messagingSenderId: '405431192912',
    projectId: 'delarship-adf14',
    authDomain: 'delarship-adf14.firebaseapp.com',
    storageBucket: 'delarship-adf14.firebasestorage.app',
    measurementId: 'G-80V2L2JPNP',
  );

}